name:                googleapis-unofficial
version:             0.1.0.1
github:              "lucasdicioccio/googleapis-unofficial"
license:             BSD3
author:              "Lucas DiCioccio"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2018 Lucas DiCioccio"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Generated proto-lens code for googleapis.
category:            GoogleApis

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/corecursive-main#readme>

dependencies:
- base >= 4.7 && < 5
- proto-lens
- proto-lens-protoc

library:
  source-dirs: gens
